dependencies:
- name: mariadb
  version: ~7.1.0
  repository: file://./charts/mariadb
  condition: mariadb.enabled
- name: redis
  version: ~10.0.1
  repository: file://./charts/redis
  condition: redis.enabled
